


exports ['error'] = function (assert){

  throw new Error("INTENSIONAL ERROR");

}
